### ISSUE TITLE
Hi issue with foreign key duplicate

### ISSUE THREAD

**Issue by karen-hikesupport** [pysco68/Pysco68.MySQL.FixedMigrationsGenerator#2]
Hi 

i have created the table which have two foreign key association with same table, but generator has generate three index key for this.

Example : 
 public class ProductExtra : FullAuditedPassiveEntity
    {
        public virtual Int32 ProductId { get; set; }
        public virtual Int32 ExtraItemId { get; set; }
        [ForeignKey("ProductId")]
        public virtual Product Product { get; set; }
        [ForeignKey("ExtraItemId")]
        public virtual Product ExtraItem { get; set; }
    }

Generate column below 
    id, productId, ExtraItemId, Product_Id

Product_Id this one generate automatically with foreign key also please help to us

**Comment by pysco68** [comment]
Hello,

the columns are being generated from the model that EF build prior to generating SQL code. If there's an extra IX appearing hear, that's probably related to your model configuration.

I can guarantee that the fixed migrations generator doesn't behave differently than the plain Oracle one in this regard.

**Comment by karen-hikesupport** [comment]
Hi,


yes agree with him, but here you can see our model in example.


it was perfect in sqlserver generation but they created issue with my sql generator.


regards

kamlesh




________________________________
