### ISSUE TITLE
issue while drop key with migration

### ISSUE THREAD

**Issue by karen-hikesupport** [pysco68/Pysco68.MySQL.FixedMigrationsGenerator#3]
Hi,

Its working perfect while migration with new foreign key and we are happy with your solution about fixes.
But there has minor issue on drop foreign key with migration. please correct it me if have any fixes for this issue.

Error while migration :  
MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot drop index 'IX_RegisterId': needed in a foreign key constraint

Regards
Karen

**Comment by pysco68** [comment]
Hi,

could you show me the migration code? It's a bit hard to understand the situation just as per your description. This might be related to a specific behaviour of MySQL vs. SQL Server; with MySQL you must drop the foreign key relation prior to dropping the index.

So it might just be a dumb operations order related issue. I don't think my generator can fix this in code as I'm not aware of any configuration possibility in this particular regard.
